ctitle: Holly Figueroa
logo: /docs/assets/img/Picture1.png
description:
  <p align="left">
  Data Science Graduate Student
  <br><br>
  <em>I am passionate about social good, mental health, and wellness. My hope is to use data science and analytics towards these values.</em>
  <br><br>
  </p>
theme: jekyll-theme-minimal
