ctitle: Holly Figueroa
logo: /docs/assets/img/hpf1.png
description:
  <p align="justify">
  Data Science Graduate Student
  <br><br>
  Science degree earnings in psychology and sociology laid a solid foundation for research methods, statistics, and data handling that helped inspire my transition to data science. I am passionate about social good, mental health, and wellness. My hope is to use data science and analytics towards these values.
  <br><br>
  </p>
theme: jekyll-theme-minimal
