ctitle: Holly Figueroa
logo: /docs/assets/img/hpf1.png
description:
  <p align="left">
  Data Science Graduate Student
  <br><br>
  <p><em>I am passionate about social good, mental health, and wellness. My hope is to use data science and analytics towards these values.<em/><p>
  <br><br>
  </p>
theme: jekyll-theme-minimal
